// Real, unedited customer language pasted directly from Tatay Pump Services'
// Google Business Profile review page (fetched 2026-09-22).
// Google's own stated total: 4.9 stars from 468 reviews (see structuredData.ts
// aggregateRating, which uses that platform-reported total, not this count).
// Loaded here: 99 reviews, all 5-star (no reviews below the 4-star
// threshold appeared on the page at capture time).
// Excluded: the very first card on the page, because the reviewer's name was cut
// off where the pasted text began mid-card — dropped rather than guessed.
// Quotes ending in "…" are Google's own truncated preview text (the "View full
// review" cutoff) — shown as-is, not fabricated or completed.
export interface GoogleReview {
  name: string;
  quote: string;
  date: string;
  rating: 5;
}

export const googleReviews: GoogleReview[] = [
  { name: 'michael herman', quote: 'Probably the nicest and professional company I have worked with. My custom constant pressure irrigation system is…', date: '13 weeks ago', rating: 5 },
  { name: 'Tracie Needham', quote: 'We called TATAY on a Friday night due to no water issues. They were out on Saturday morning with a quote to install the…', date: '34 weeks ago', rating: 5 },
  { name: 'Rebecca Spicer', quote: 'Tatay was fabulous . They were prompt on a Labor Day Saturday and replaced our pump and bladder. They were respectful of…', date: '2 weeks ago', rating: 5 },
  { name: 'Constance', quote: 'Tatay was awesome from start to finish. They went out of their way to help me get water back in my house quickly. They…', date: '9 weeks ago', rating: 5 },
  { name: 'Roberto Rivera', quote: 'Great service, highly recommended!…', date: '12 weeks ago', rating: 5 },
  { name: 'Ben Koch', quote: 'Thank you, Tatay Pump Services, for your professionalism, prompt response, and honesty!…', date: '15 weeks ago', rating: 5 },
  { name: 'daniel fisher', quote: 'These guys came in at the last minute for an emergency, quickly and expertly diagnosed the problem, provided a quick…', date: '2 weeks ago', rating: 5 },
  { name: 'Margaret Mitchell', quote: 'We recently had to have a new well put in. After trying a "local" company and again not being able to get a hold of…', date: '11 weeks ago', rating: 5 },
  { name: 'Steven Haney', quote: 'Very professional with excellent customer service. I discovered a main line water leak. I called them at 3:15 pm they…', date: '33 weeks ago', rating: 5 },
  { name: 'Megan Fuller', quote: 'I cannot thank these guys enough!!! Our water was fine one day and then just shut off the next. We called two different…', date: '11 weeks ago', rating: 5 },
  { name: 'Caleb Theriault', quote: 'The Taytay crew were awesome to work with, from scheduling and estimating, to the actual replacement. They were clear,…', date: '13 weeks ago', rating: 5 },
  { name: 'Norman Vesprini', quote: 'Problem with your well pump? Call Tatay Pump Services now! They were one of the most professional outfits I\'ve hired in…', date: '12 weeks ago', rating: 5 },
  { name: 'John Hallam', quote: 'We had a great experience with this company and highly recommend them.…', date: '20 weeks ago', rating: 5 },
  { name: 'Jennifer Crist', quote: 'We were recommended to Tatay from a plumbing company after having issues with hot water crossing over to our cold lines.…', date: '26 Jul 2025', rating: 5 },
  { name: 'Brandi', quote: 'We are deeply grateful to Tatay Well Services for their exceptional work in installing our brand-new well system. Our…', date: '12 Aug 2025', rating: 5 },
  { name: 'Carlos Checkcinco', quote: 'Tatay moves FAST! I called every company in the area and they\'re the only ones who took the time to give an in-person…', date: '10 weeks ago', rating: 5 },
  { name: 'Jeff Zobrosky', quote: 'I am very happy with the job Lucas and Doug did for us. They always on time and very considerate of our property . They…', date: '43 weeks ago', rating: 5 },
  { name: 'James Granger', quote: 'The speed and professionalism of Tatay and their technicians was excellent. I will not call any other plumbing house…', date: '8 weeks ago', rating: 5 },
  { name: 'Eric Williams', quote: 'My pump in my well went out. I contacted Tatay and Lucas promptly responded. They came out the next day and worked…', date: '14 weeks ago', rating: 5 },
  { name: 'Dana Florea', quote: 'Beehler and Tatay Pump provided professional, efficient, and experienced service when we needed it most. Our water tank…', date: '24 weeks ago', rating: 5 },
  { name: 'Briana Reitz', quote: 'We have worked with Tatay Pump Services before and would highly recommend them. We had an emergency that happened over…', date: '5 weeks ago', rating: 5 },
  { name: 'Tracy Tracy', quote: 'Amazing, professional, kind, direct explanations from Lucas and his peer. Came right out within couple hours of my…', date: '27 weeks ago', rating: 5 },
  { name: 'David Simons', quote: 'Over the years I have found Tatay Pump Services to be responsive and helpful when we had well issues. I recently called…', date: '16 weeks ago', rating: 5 },
  { name: 'Tia', quote: 'I love this company! The amount of transparency we\'d received made all the difference to us.…', date: '27 weeks ago', rating: 5 },
  { name: 'Sean Horwarth', quote: 'I can\'t recommend Tatay Well Service enough. After dealing with intermittent issues with our old well, we tried calling…', date: '33 weeks ago', rating: 5 },
  { name: 'Steve Kurzhal', quote: 'Bladder tank had to be replaced. We got on the schedule within 48 hrs. Mike and his team were respectful of our…', date: '18 weeks ago', rating: 5 },
  { name: 'Jim Brumbaugh', quote: 'Beehler & company did another great job. Well pump last September and new tank after he they came out last week to…', date: '49 weeks ago', rating: 5 },
  { name: 'Kim Whisler', quote: 'I called Tatay at 2:05 pm today because my well pump was running continuously. By 3:35 they had called, come out and…', date: '16 weeks ago', rating: 5 },
  { name: 'E O', quote: 'Job well done! They were able to come out the following day after I submitted a request for an appointment. We needed…', date: '19 weeks ago', rating: 5 },
  { name: 'Matt Herm', quote: 'Awesome service! We had a well issue that a plumber worked on for a few days without any luck. Tatay came the same day…', date: '33 weeks ago', rating: 5 },
  { name: 'Pam French', quote: 'They helped my client / seller that was on a time frame for the closing on his home. Gary reacted quickly and got the repair made on time! Great communication and customer service. Thank you!', date: '12 weeks ago', rating: 5 },
  { name: 'Seth Watkins', quote: 'Fantastic from start to finish. Called around 5am and had a call back before the business opened to set up a time the…', date: '13 weeks ago', rating: 5 },
  { name: 'Destiny Wilson', quote: 'Extremely FAST response time! I called on a Friday night about 10pm for a non-emergency and received a call Saturday by…', date: '24 weeks ago', rating: 5 },
  { name: 'Deborah Dorsch', quote: 'I called at 8am for having no water, every person I interacted with was very kind and understanding. They had it completely up and running again in about 2 hours total. Highly recommend. Very professional team!', date: '10 weeks ago', rating: 5 },
  { name: 'Edward Jurkovic', quote: 'I had an emergency well situation come up on Memorial Day weekend. I was able to connect with them in the evening and get things sorted out quickly and efficiently right away. Highly recommend.', date: '17 weeks ago', rating: 5 },
  { name: 'Richard Seall', quote: 'Gary was very thorough and explained everything to me to make it easy to understand. I could tell he was very…', date: '22 weeks ago', rating: 5 },
  { name: 'Melody Wilson', quote: 'Tatty is a class act company. We called them 10:00 and the arrived about an hour later. Completely professional with…', date: '15 weeks ago', rating: 5 },
  { name: 'Mark Pease', quote: 'Tatay Well and Pump Service again has served us well. Promptly and reasonably. The guys cleaned up after themselves and were professional and courteous would recommend them to anyone.', date: '11 weeks ago', rating: 5 },
  { name: 'Rachel Steinmetz', quote: 'Tatay Pump Services is professional, courteous and reasonably priced. They showed up on time and figured out our water pressure problem quickly. I highly recommend them.', date: '15 weeks ago', rating: 5 },
  { name: 'Foot Solutions Granger - Indiana', quote: 'I left a message on line this morning that I needed help with a leak in the basement. Beehler called first thing and…', date: '13 weeks ago', rating: 5 },
  { name: 'Stephen Lavelle', quote: 'We were very pleased with the work done by and the responsiveness from Tatay Pump Service. They came out within 24 hours - on a Saturday - and had us back up and running quickly and cleanly. Thank you!', date: '9 Sept 2025', rating: 5 },
  { name: 'chris laware', quote: 'We had no water pressure at our home and Tatay came out and fixed it in a couple hours. It turned out to be a bad pump…', date: '29 weeks ago', rating: 5 },
  { name: 'Thomas Heminger', quote: 'Thank you for prompt, professional, and reliable service to my well tank. I am a satisfied customer over many years…', date: '22 weeks ago', rating: 5 },
  { name: 'Gary Krol', quote: 'Excellent professional service and repair to our well pump system. They made arrangements to meet me on a Saturday…', date: '22 weeks ago', rating: 5 },
  { name: 'Wendy McMillen', quote: 'Totally recommend this company! We had an emergency on a major holiday weekend and while everyone else told me to call…', date: '11 weeks ago', rating: 5 },
  { name: 'Julie Wilken', quote: 'They were very professional, went above and beyond their job duties. (They worked, in below zero temperatures). Very…', date: '31 weeks ago', rating: 5 },
  { name: 'Lindsay Mathews', quote: 'The guys who came out (sorry forgot names) were very professional and got the job done fast. I am so thankful for them…', date: '34 weeks ago', rating: 5 },
  { name: 'K GAEDTKE', quote: 'Service call to replace a water tank and gauge. Mike and Gary were very efficient. Kept me informed as to their arrival…', date: '28 weeks ago', rating: 5 },
  { name: 'David Clore', quote: 'When I had a well problem, Tatay\'s team showed up on a Friday afternoon on short notice. They fixed everything for a…', date: '26 weeks ago', rating: 5 },
  { name: 'Edward Jurkovic', quote: 'Great company. Completely transparent and helpful in our time of troubles. Came to the house fixed what we needed in a professional and friendly manner. Quick response and reasonable rates.', date: '16 weeks ago', rating: 5 },
  { name: 'Matthew Toppel', quote: 'I highly recommend Tatay Pump/Well Services. Lucas and Doug went above and beyond on our installation. They are both…', date: '28 weeks ago', rating: 5 },
  { name: 'Jake Downs', quote: 'Fast, upfront, transparent, friendly, and effective. This was my first time needing my well worked on, and they were…', date: '38 weeks ago', rating: 5 },
  { name: 'Kenneth Nemes', quote: 'Quick response to initial telephone call to review problem and schedule visit. Once on site, Beehler and his assistant…', date: '16 weeks ago', rating: 5 },
  { name: 'Larry B', quote: 'Tatay responded quickly to a pump valve failure. Came out first thing in the morning and fixed the problem. Mike and John did a great job! Highly recommend Tatay.', date: '23 weeks ago', rating: 5 },
  { name: 'Karl Karch', quote: 'Fantastic customer service and professionalism. I called Tatay early in the morning before normal working hours and left…', date: '34 weeks ago', rating: 5 },
  { name: 'NICOLE BORTON', quote: 'Five stars is not enough! I truly cannot say enough good things…', date: '39 weeks ago', rating: 5 },
  { name: 'Siobhan Bruegmann', quote: 'When my well head got run over my a snowmobile, they came out to repair it. Gary and crew were great and answered all…', date: '32 weeks ago', rating: 5 },
  { name: 'David Dyck', quote: 'Great service, friendly staff. Was having intermittent pressure issues and Mike came out the next day and fixed the problem.', date: '8 weeks ago', rating: 5 },
  { name: 'Don Napoli', quote: 'The service team was very professional, friendly and helpful. They explained everything and showed me the defective in the old pump. It was certainly necessary to change to a new water pump.', date: '13 weeks ago', rating: 5 },
  { name: 'Stephen Holmes', quote: 'Tatay was available and experienced! Their specialist came out after I was quoted $8,000 by another company for a new…', date: '25 weeks ago', rating: 5 },
  { name: 'Angela Leazenby', quote: 'The servicemen were awesome! They were skillful, knowledgeable, and friendly as well. They did a fantastic job repairing our well!', date: '15 weeks ago', rating: 5 },
  { name: 'Kristin Perkins', quote: 'Tatay always does such amazing work!! Very professional and honest!!! Thank you Lucas, Beehler and the rest of the crew.', date: '18 weeks ago', rating: 5 },
  { name: 'Christopher Forbes', quote: 'The guys who came to my house were very courteous and explained everything fully. You never really know if you are…', date: '12 weeks ago', rating: 5 },
  { name: 'Patrick Zehner', quote: 'They ran into some problems with my 38 year old system. They stuck with with it until it was completed. I would refer them. Good work. Fair price.', date: '19 weeks ago', rating: 5 },
  { name: 'David Isaacson', quote: 'Beehler and his team at Tatay were extremely timely, professional, and thorough. The system that they had installed for…', date: '23 weeks ago', rating: 5 },
  { name: 'Barbara Havens', quote: 'They did outstanding work. We would use them again in a heartbeat. Honesty is hard to find. Our water went out on Friday…', date: '31 weeks ago', rating: 5 },
  { name: 'Craig Kapson', quote: 'Our house was struck by lightning and we lost all water. I called Tatay Pump Service and within an hour they had people…', date: '33 weeks ago', rating: 5 },
  { name: 'Brant Hoggatt', quote: 'Could not recommend their services more! Everyone was very helpful and kind, they were very thorough and prompt, and Lucas and Beehler were excellent at communicating and engaging with.', date: '22 weeks ago', rating: 5 },
  { name: 'Manjula Musunuru', quote: 'Very prompt and always on time.willing to take time to analyze the problem and fix it. I would definitely recommend them.', date: '8 weeks ago', rating: 5 },
  { name: 'Chris Karney', quote: 'From the start of the conversation after normal business hours from One of the owners of Tatay to the representation of…', date: '47 weeks ago', rating: 5 },
  { name: 'kim putney', quote: 'Great service and vey prompt! We have a business that can\'t afford to be down with a broken well. The guys were here within an hour! Everything fixed by the end of the day…', date: '37 weeks ago', rating: 5 },
  { name: 'Geoffrey Paydon', quote: 'Tatay responded very quickly to a weekend messenger service when my rental property\'s well failed. I spoke to them…', date: '35 weeks ago', rating: 5 },
  { name: 'Daniel Abel', quote: 'I have never used Tatay Pump in the past, but I called them in the morning and had technicians out at the house by…', date: '29 weeks ago', rating: 5 },
  { name: 'Angela Hurlbutt', quote: 'The Tatay crew were knowledgeable, friendly and very helpful. They made the entire process easy, and took time to explain everything clearly.', date: '13 weeks ago', rating: 5 },
  { name: 'kevin jacks', quote: 'From the initial estimate to the finished well we were satisfied. The crew had ample knowledge of their job and went…', date: '4 Jun 2025', rating: 5 },
  { name: 'Stacey Heying', quote: 'Very quick response time from the time I had called. Gary and Mike came out for the service call and did a great job. Very nice guys', date: '29 weeks ago', rating: 5 },
  { name: 'Sara Burger', quote: 'Gary was wonderful working with! Very knowledgeable and informational.…', date: '10 weeks ago', rating: 5 },
  { name: 'Ty', quote: 'Answered my service call the same day and addressed all my concerns. Explained everything every step of the way and I would recommend to my friends and family. 5 star service!', date: '13 weeks ago', rating: 5 },
  { name: 'Mark Stapleton', quote: 'Very happy w/there service, and so fast. I would recommend them 2 anyone. 5 stars all the way.', date: '15 weeks ago', rating: 5 },
  { name: 'Tyler Bellin', quote: 'We had an emergency and they were extremely quick to respond. The work was done in a very professional manner and the service was top notch.', date: '22 weeks ago', rating: 5 },
  { name: 'Terry Myers', quote: 'Awesome same day service when our submersible well pump went out. Beehler had his team to our home in a very short time…', date: '45 weeks ago', rating: 5 },
  { name: 'Greg Towner', quote: 'The technicians were on time, very courteous, extremely knowledgeable and took the time to answer my questions in a way that I was able to understand. Highly recommend them.', date: '24 weeks ago', rating: 5 },
  { name: 'Angie Evans', quote: 'I can not thank Tatay enough for their service. I didn\'t understand how water pumps or well systems worked. I had no…', date: '1 Feb 2025', rating: 5 },
  { name: 'Michelle Paluzzi', quote: 'I called for emergency service on a Friday night. Had a tech out first thing Saturday morning. They brought everything…', date: '32 weeks ago', rating: 5 },
  { name: 'Mitch Yoder', quote: '"Tatay Pump Service came out and fixed our water issue fast and professionally. They were extremely nice, knowledgeable,…', date: '28 weeks ago', rating: 5 },
  { name: 'Todd Snyder', quote: 'They were able to help my 92 year old father who\'s well was leaking. Fast response and extra mile to help my dad!', date: '13 weeks ago', rating: 5 },
  { name: 'Phil Schreiber', quote: 'They checked out our system and decided that it only needed some pressure in the tank. No new motor. No cleaning the filter. Just a $145 service call.', date: '8 weeks ago', rating: 5 },
  { name: 'Ethan Chappell', quote: 'We had an absolutely outstanding experience with Tatay! From start to finish, their professionalism, communication, and…', date: '28 May 2025', rating: 5 },
  { name: 'Pat Klein', quote: 'I first called Tatay Pump Services for an inspection on a well they installed about 25 years ago. They were very…', date: '48 weeks ago', rating: 5 },
  { name: 'jim dycus', quote: 'The 2 men were extremely polite, very knowledgeable and they took the time to explain everything and to thoroughly answer every question. I highly recommend them.', date: '9 weeks ago', rating: 5 },
  { name: 'Austin Bencsics', quote: 'Our well pump quit on us the night before. I called first thing in the morning before they opened and I actually…', date: '51 weeks ago', rating: 5 },
  { name: 'Marc Riedel', quote: 'My pump went out Sunday night. I called the 24-hour call center and had an appointment the next day. It only took a few…', date: '8 Jun 2025', rating: 5 },
  { name: 'Chris Clifford', quote: 'Pump was short cycling, called in the morning and they were able to have the replacement bladder installed by the afternoon.', date: '5 weeks ago', rating: 5 },
  { name: 'Tom Tom', quote: 'Beeler (3rd gen) came out after an early morning phone call about us having a well pressure issue. He was doing a…', date: '29 Jun 2025', rating: 5 },
  { name: 'Marlene Korenstra', quote: 'What fabulous service!! We discovered a big problem this morning at 9:00am, and made the call to Tatay Pump Service.…', date: '20 Aug 2025', rating: 5 },
  { name: 'Ron K Ward Sr', quote: 'Gary and Mike did a super job. Reviewed the issue, explained options and provided cost . Service was fast and quite, shoes were removed and concern for our living space . Highly recommended..', date: '32 weeks ago', rating: 5 },
  { name: 'John Nowicki', quote: 'My tank bladder ruptured. Mike and John were knowledgeable, professional, and did a great job replacing the broken tank.', date: '15 weeks ago', rating: 5 },
  { name: 'Patricia Fulcher', quote: 'Tatay pump services did a great job, kept us informed of what they were doing, explained what they did when finished, courteous, cleaned up area well.... great job everyone!', date: '9 weeks ago', rating: 5 },
  { name: 'Chris Landis', quote: 'Great company. Fast response, professional service, and very easy to work with. Highly recommend!', date: '18 weeks ago', rating: 5 },
];
