// Real, unedited customer language pasted directly from Tatay Pump Service's
// Yelp business page (fetched 2026-09-22).
// Loaded here: 15 reviews — all of Yelp's currently-recommended reviews
// shown on the page at capture time.
// Excluded: 6 additional reviews Yelp itself labels "not currently recommended"
// (Yelp's own filtering, not fetched — Yelp does not surface their text on the
// public page).
// No per-review star rating is included: Yelp's star icons are images and are
// lost on copy/paste, so rather than guess a rating, these are shown as
// Yelp-recommended reviews without an assigned star count.
export interface YelpReview {
  name: string;
  location: string;
  quote: string;
  date: string;
}

export const yelpReviews: YelpReview[] = [
  { name: 'Ron N.', location: 'Granger, IN', quote: 'New constant pressure installed at home. Terrific service and exceptional communication. System is working just fine.', date: 'Aug 12, 2026' },
  { name: 'Ilene S.', location: 'Edwardsburg, MI', quote: 'Excellent customer service and communication. Fair pricing and accurate on arrival time. Five star company. Very satisfied.\nIlene and Rick Sheffer', date: 'Aug 22, 2025' },
  { name: 'Paula G.', location: 'Elkhart, IN', quote: 'We had no water, we called them out. They gave us a estimate. Had to get the finances together. Called them out very friendly. Exactly what they estimated. Made sure everything was running smoothly. Fast same day service. We couldn\'t be happier to have quality work done by a family business and water before Thanksgiving BIG THANKS!!', date: 'Nov 17, 2023' },
  { name: 'Lisa S.', location: 'Granger, IN', quote: 'I had a VERY noisy pump that actually woke me up if I was sleeping and it went on. It was 30+ years old. Had great communications with the folks at Tatay. They replaced my pump and it is SO quiet! Wish I had them do this a couple of years ago. Highly recommended!', date: 'Jun 13, 2023' },
  { name: 'Pretty S.', location: 'New Paris, IN', quote: 'My father needed his well pump replaced, and I chose Tatay due to their ratings. We were not disappointed!\n\nI received a call from Lucas, who made it as simple as texting a photo to discern what kind of pump was needed- and he arrived merely 2 hours later to install it!\n\nHe offered my older veteran father a discount, and worked with him on the cost of a big issue that was discovered after the quote was given.\n\nThey were fast, professional, and very kind.', date: 'Mar 16, 2021' },
  { name: 'Patrick O.', location: 'Granger, IN', quote: 'These guys are awesome! Our water stopped working at about 9 o\'clock the night before Fourth of July. We gave these guys a call and got a call back within 15 minutes. They had us try a couple things over the phone and when those didn\'t work, they said they\'d get a crew out to the house the next morning. We got a call at 8:30 the next morning saying they\'d be at the house in fifteen minutes. On the Fourth of July! They were here 15 minutes later, looked at everything, explained the issue and fixed it all quickly and efficiently. No problems! The customer service was excellent. Very polite. When they explained everything they also went over the pricing structure which was very reasonable. These guys are father-and-son and work well together. They turned what could have been a rough experience into a positive encounter all around. Thanks a lot!', date: 'Jul 4, 2022' },
  { name: 'Robin T.', location: 'San Francisco, CA', quote: 'This is a fantastic company. We were having problems with our well, and thought that the pump was going out. We called them in the morning, they came out later that day and were able to replace our pump and a worn out breaker by 2:00 p.m. that day! They were professional, courteous and fair. Such a relief to feel safe and secure with such a reputable company! Thank you - Mike and Robin, Niles, Mi.', date: 'Jan 30, 2021' },
  { name: 'Steve G.', location: 'Scotts Hill, TN', quote: 'First to Review\nI hired Tatay Well Drilers to put in a new constant velocity well pump to replace our aging traditional pump about 4 months ago. The service then was top notch and they even repaired some shortcoming from the original install just so that it was "right".\n\nFast forward to last week and my well runs non stop. May have been that way for days or weeks without me knowing. They came out right away and pulled to pump to fix a manufacturer\'s defect. No hassle, no charge, excellent service.\n\nIf you need a new pump, well, or service, I highly recommend Tatay and would galdly hire them again if I need help.', date: 'Mar 13, 2010' },
  { name: 'Laura F.', location: 'Niles, MI', quote: 'We had a water leak and then lost water pressure in our well. We called them mid morning and the lady answering the phone was very polite, took our info and told us that someone would contact us within 15-20 mins. We then received a call from Lucas within the 15 mins, and we explained our situation. Lucas informed us they were in the middle of a job but would reach out to us as soon as they could head our way. They were at our house in less than 2 hours, accessed the issues, quoted us and had everything fixed within an hour. Lucas and his partner were very courteous and they removed their shoes every time they entered the house. These guys are the BEST and we would not hesitate to call them for future issues. A+++++ service !!!', date: 'Sep 6, 2021' },
  { name: 'Ed B.', location: 'Elkhart, IN', quote: 'My pump is surging and they told me what was probably going to be wrong. They said they could show up the next day and they did. They did the repairs as promised and under budget. Very happy with them and highly recommend these people.', date: 'Dec 18, 2019' },
  { name: 'Lauren W.', location: 'Elkhart, IN', quote: 'The gentlemen that came to our house were excellent very polite they worked quick fix their problem same day we are only without water for a few hours. I would recommend them for Well Services', date: 'Feb 15, 2017' },
  { name: 'Ed N.', location: 'South Bend, IN', quote: 'Mr Tatay and Son installed a new submersible pump on my 120 foot water well.\nThey came within a few hours of my call, were polite, professional and\nthorough. It took them less than two hours to do the whole job.\n5 stars is not high enough', date: 'May 31, 2018' },
  { name: 'Kimberly T.', location: 'Granger, IN', quote: 'Our well pump went out at our lake house the day before renters were scheduled to check in. Needless to say, I was worried that we wouldn\'t have it repaired before they came. I called Tatay because a friend recommended them. Beeler was friendly, professional and promptly took care of our well pump and he was significantly less expensive than the other guy we called. Highly recommend!', date: 'Jul 8, 2014' },
  { name: 'Shaun S.', location: 'South Bend, IN', quote: 'Left a message with their answering service after 7PM at night and received a call back from the actual owner of the company within an hour! That alone blew me away. He was extremely friendly and was already working with me over the phone to go over what needed to be done -- getting detailed information, etc. instead of just scheduling an appointment and wasting time.\n\nDespite recent severe storms in the area he was able to make it over at 10AM two business days after that night. I got a phone call on my cell from him personally to meet me at the house and they had actually beat that time. Instead of standing around and waiting for me they had completely prepped for the work (unloaded excavating equipment, tools, etc.) They even used platforms to drive the equipment over as to not mess up the lawn. Once work started they were incredibly efficient. The work they did for me was not easy stuff. Excavating down around landscaping to get to a cracked well casing and repairing it while not making things worse with heavy equipment takes skill and care.\n\nTatay has a good reputation for a reason.', date: 'Jun 29, 2016' },
  { name: 'Brian G.', location: 'South Bend, IN', quote: 'Had trouble with my water supply, so i called Tatay. Talked with a secratary she took my number and in less than an hour the owner called me back. I explained my problem with him, he said he would be at my house in 2 hours, yes that quick, yes he was at my house within 2 hours. We discussed the problem he checked my wellpump with a meter he told me what the problem was , explained the problem with me , gave me a price . I said yes do the work. The work was professional , clean and he and his worker was done. The problem was fixed, yes that quick, i would tell everyone to use Tatay. THANK YOU TATAY for your service. Brian G', date: 'Feb 7, 2016' },
];
